name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *" # Runs daily at 6:00 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          #destination-folder: leetcode-solutions # Optional folder for submissions
          verbose: true
          commit-header: "[LeetCode Sync]"
